export interface Station {
  id: string;
  name: string;
  brand: string;
  address: string;
  suburb: string;
  postcode: string;
  state: string;
  latitude: number;
  longitude: number;
  hasToilet: boolean;
  hasShop: boolean;
  hasCarwash: boolean;
  loyaltyProgram?: string;
  loyaltyDiscountCents?: number;
}

export const STATIONS: Station[] = [
  // ─── Brisbane CBD area ───────────────────────────────────────────────
  {
    id: 'station-001',
    name: 'BP Fortitude Valley',
    brand: 'BP',
    address: '283 Wickham Street',
    suburb: 'Fortitude Valley',
    postcode: '4006',
    state: 'QLD',
    latitude: -27.4575,
    longitude: 153.0350,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-002',
    name: '7-Eleven Fortitude Valley',
    brand: '7-Eleven',
    address: '79 Brunswick Street',
    suburb: 'Fortitude Valley',
    postcode: '4006',
    state: 'QLD',
    latitude: -27.4590,
    longitude: 153.0370,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-003',
    name: 'Shell Coles Express South Brisbane',
    brand: 'Coles Express',
    address: '168 Grey Street',
    suburb: 'South Brisbane',
    postcode: '4101',
    state: 'QLD',
    latitude: -27.4780,
    longitude: 153.0180,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-004',
    name: 'Ampol Woolworths Woolloongabba',
    brand: 'Ampol',
    address: '769 Stanley Street',
    suburb: 'Woolloongabba',
    postcode: '4102',
    state: 'QLD',
    latitude: -27.4865,
    longitude: 153.0350,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-005',
    name: 'United Petroleum West End',
    brand: 'United',
    address: '52 Montague Road',
    suburb: 'West End',
    postcode: '4101',
    state: 'QLD',
    latitude: -27.4790,
    longitude: 153.0090,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-006',
    name: 'Metro Fortitude Valley',
    brand: 'Metro',
    address: '410 St Pauls Terrace',
    suburb: 'Fortitude Valley',
    postcode: '4006',
    state: 'QLD',
    latitude: -27.4560,
    longitude: 153.0290,
    hasToilet: false,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-007',
    name: 'Shell South Brisbane',
    brand: 'Shell',
    address: '48 Vulture Street',
    suburb: 'South Brisbane',
    postcode: '4101',
    state: 'QLD',
    latitude: -27.4810,
    longitude: 153.0220,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-008',
    name: '7-Eleven Woolloongabba',
    brand: '7-Eleven',
    address: '185 Logan Road',
    suburb: 'Woolloongabba',
    postcode: '4102',
    state: 'QLD',
    latitude: -27.4900,
    longitude: 153.0400,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },

  // ─── North Brisbane ──────────────────────────────────────────────────
  {
    id: 'station-009',
    name: 'BP Chermside',
    brand: 'BP',
    address: '700 Gympie Road',
    suburb: 'Chermside',
    postcode: '4032',
    state: 'QLD',
    latitude: -27.3860,
    longitude: 153.0310,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-010',
    name: 'Shell Coles Express Chermside',
    brand: 'Coles Express',
    address: '662 Gympie Road',
    suburb: 'Chermside',
    postcode: '4032',
    state: 'QLD',
    latitude: -27.3880,
    longitude: 153.0320,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-011',
    name: '7-Eleven Chermside',
    brand: '7-Eleven',
    address: '718 Gympie Road',
    suburb: 'Chermside',
    postcode: '4032',
    state: 'QLD',
    latitude: -27.3845,
    longitude: 153.0305,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-012',
    name: 'Ampol Aspley',
    brand: 'Ampol',
    address: '1385 Gympie Road',
    suburb: 'Aspley',
    postcode: '4034',
    state: 'QLD',
    latitude: -27.3650,
    longitude: 153.0260,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-013',
    name: 'United Petroleum Aspley',
    brand: 'United',
    address: '1421 Gympie Road',
    suburb: 'Aspley',
    postcode: '4034',
    state: 'QLD',
    latitude: -27.3630,
    longitude: 153.0250,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-014',
    name: 'Puma Nundah',
    brand: 'Puma',
    address: '1220 Sandgate Road',
    suburb: 'Nundah',
    postcode: '4012',
    state: 'QLD',
    latitude: -27.4020,
    longitude: 153.0590,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-015',
    name: 'BP Nundah',
    brand: 'BP',
    address: '1190 Sandgate Road',
    suburb: 'Nundah',
    postcode: '4012',
    state: 'QLD',
    latitude: -27.4040,
    longitude: 153.0600,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-016',
    name: 'Puma Strathpine',
    brand: 'Puma',
    address: '335 Gympie Road',
    suburb: 'Strathpine',
    postcode: '4500',
    state: 'QLD',
    latitude: -27.3050,
    longitude: 152.9910,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
  },
  {
    id: 'station-017',
    name: 'Shell Strathpine',
    brand: 'Shell',
    address: '395 Gympie Road',
    suburb: 'Strathpine',
    postcode: '4500',
    state: 'QLD',
    latitude: -27.3030,
    longitude: 152.9900,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-018',
    name: '7-Eleven Kedron',
    brand: '7-Eleven',
    address: '158 Gympie Road',
    suburb: 'Kedron',
    postcode: '4031',
    state: 'QLD',
    latitude: -27.4120,
    longitude: 153.0300,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-019',
    name: 'Ampol Kedron',
    brand: 'Ampol',
    address: '200 Gympie Road',
    suburb: 'Kedron',
    postcode: '4031',
    state: 'QLD',
    latitude: -27.4100,
    longitude: 153.0290,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-020',
    name: 'Liberty Strathpine',
    brand: 'Liberty',
    address: '421 Gympie Road',
    suburb: 'Strathpine',
    postcode: '4500',
    state: 'QLD',
    latitude: -27.3010,
    longitude: 152.9890,
    hasToilet: false,
    hasShop: true,
    hasCarwash: false,
  },

  // ─── South Brisbane ──────────────────────────────────────────────────
  {
    id: 'station-021',
    name: 'Shell Coles Express Mt Gravatt',
    brand: 'Coles Express',
    address: '1825 Logan Road',
    suburb: 'Mt Gravatt',
    postcode: '4122',
    state: 'QLD',
    latitude: -27.5340,
    longitude: 153.0780,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-022',
    name: 'BP Mt Gravatt',
    brand: 'BP',
    address: '1780 Logan Road',
    suburb: 'Mt Gravatt',
    postcode: '4122',
    state: 'QLD',
    latitude: -27.5320,
    longitude: 153.0770,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-023',
    name: 'Ampol Woolworths Carindale',
    brand: 'Ampol',
    address: '1151 Creek Road',
    suburb: 'Carindale',
    postcode: '4152',
    state: 'QLD',
    latitude: -27.5050,
    longitude: 153.1030,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-024',
    name: '7-Eleven Carindale',
    brand: '7-Eleven',
    address: '1089 Creek Road',
    suburb: 'Carindale',
    postcode: '4152',
    state: 'QLD',
    latitude: -27.5070,
    longitude: 153.1010,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-025',
    name: 'BP Springwood',
    brand: 'BP',
    address: '3370 Pacific Motorway',
    suburb: 'Springwood',
    postcode: '4127',
    state: 'QLD',
    latitude: -27.5910,
    longitude: 153.1290,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-026',
    name: 'Shell Coles Express Springwood',
    brand: 'Coles Express',
    address: '3388 Pacific Motorway',
    suburb: 'Springwood',
    postcode: '4127',
    state: 'QLD',
    latitude: -27.5930,
    longitude: 153.1310,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-027',
    name: 'United Petroleum Browns Plains',
    brand: 'United',
    address: '28 Browns Plains Road',
    suburb: 'Browns Plains',
    postcode: '4118',
    state: 'QLD',
    latitude: -27.6550,
    longitude: 153.0530,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-028',
    name: '7-Eleven Browns Plains',
    brand: '7-Eleven',
    address: '56 Browns Plains Road',
    suburb: 'Browns Plains',
    postcode: '4118',
    state: 'QLD',
    latitude: -27.6570,
    longitude: 153.0540,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-029',
    name: 'Ampol Logan',
    brand: 'Ampol',
    address: '3470 Pacific Highway',
    suburb: 'Logan',
    postcode: '4114',
    state: 'QLD',
    latitude: -27.6390,
    longitude: 153.1090,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-030',
    name: 'BP Logan',
    brand: 'BP',
    address: '3510 Pacific Highway',
    suburb: 'Logan',
    postcode: '4114',
    state: 'QLD',
    latitude: -27.6410,
    longitude: 153.1100,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-031',
    name: 'Puma Sunnybank',
    brand: 'Puma',
    address: '346 Mains Road',
    suburb: 'Sunnybank',
    postcode: '4109',
    state: 'QLD',
    latitude: -27.5780,
    longitude: 153.0620,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-032',
    name: 'Shell Sunnybank',
    brand: 'Shell',
    address: '420 Mains Road',
    suburb: 'Sunnybank',
    postcode: '4109',
    state: 'QLD',
    latitude: -27.5800,
    longitude: 153.0630,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-033',
    name: 'Metro Springwood',
    brand: 'Metro',
    address: '14 Cinderella Drive',
    suburb: 'Springwood',
    postcode: '4127',
    state: 'QLD',
    latitude: -27.5890,
    longitude: 153.1270,
    hasToilet: false,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-034',
    name: 'Independent Browns Plains',
    brand: 'Independent',
    address: '110 Grand Plaza Drive',
    suburb: 'Browns Plains',
    postcode: '4118',
    state: 'QLD',
    latitude: -27.6600,
    longitude: 153.0510,
    hasToilet: false,
    hasShop: false,
    hasCarwash: false,
  },

  // ─── West Brisbane ───────────────────────────────────────────────────
  {
    id: 'station-035',
    name: 'BP Indooroopilly',
    brand: 'BP',
    address: '34 Moggill Road',
    suburb: 'Indooroopilly',
    postcode: '4068',
    state: 'QLD',
    latitude: -27.4980,
    longitude: 152.9760,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-036',
    name: 'Shell Coles Express Indooroopilly',
    brand: 'Coles Express',
    address: '68 Moggill Road',
    suburb: 'Indooroopilly',
    postcode: '4068',
    state: 'QLD',
    latitude: -27.4990,
    longitude: 152.9740,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-037',
    name: '7-Eleven Toowong',
    brand: '7-Eleven',
    address: '9 Sherwood Road',
    suburb: 'Toowong',
    postcode: '4066',
    state: 'QLD',
    latitude: -27.4840,
    longitude: 152.9890,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-038',
    name: 'Liberty Kenmore',
    brand: 'Liberty',
    address: '2088 Moggill Road',
    suburb: 'Kenmore',
    postcode: '4069',
    state: 'QLD',
    latitude: -27.5070,
    longitude: 152.9380,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-039',
    name: 'Ampol Toowong',
    brand: 'Ampol',
    address: '47 Coronation Drive',
    suburb: 'Toowong',
    postcode: '4066',
    state: 'QLD',
    latitude: -27.4820,
    longitude: 152.9870,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-040',
    name: 'Independent Fig Tree Pocket',
    brand: 'Independent',
    address: '156 Fig Tree Pocket Road',
    suburb: 'Fig Tree Pocket',
    postcode: '4069',
    state: 'QLD',
    latitude: -27.5170,
    longitude: 152.9590,
    hasToilet: false,
    hasShop: false,
    hasCarwash: false,
  },

  // ─── East Brisbane ───────────────────────────────────────────────────
  {
    id: 'station-041',
    name: 'Metro Wynnum',
    brand: 'Metro',
    address: '182 Tingal Road',
    suburb: 'Wynnum',
    postcode: '4178',
    state: 'QLD',
    latitude: -27.4540,
    longitude: 153.1610,
    hasToilet: false,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-042',
    name: 'Shell Wynnum',
    brand: 'Shell',
    address: '210 Bay Terrace',
    suburb: 'Wynnum',
    postcode: '4178',
    state: 'QLD',
    latitude: -27.4520,
    longitude: 153.1580,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-043',
    name: 'BP Manly',
    brand: 'BP',
    address: '5 Manly Road',
    suburb: 'Manly',
    postcode: '4179',
    state: 'QLD',
    latitude: -27.4590,
    longitude: 153.1700,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-044',
    name: 'Ampol Capalaba',
    brand: 'Ampol',
    address: '89 Redland Bay Road',
    suburb: 'Capalaba',
    postcode: '4157',
    state: 'QLD',
    latitude: -27.5260,
    longitude: 153.1910,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-045',
    name: '7-Eleven Capalaba',
    brand: '7-Eleven',
    address: '45 Old Cleveland Road',
    suburb: 'Capalaba',
    postcode: '4157',
    state: 'QLD',
    latitude: -27.5240,
    longitude: 153.1890,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-046',
    name: 'United Petroleum Wynnum',
    brand: 'United',
    address: '340 Wynnum Road',
    suburb: 'Wynnum',
    postcode: '4178',
    state: 'QLD',
    latitude: -27.4560,
    longitude: 153.1560,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },

  // ─── Ipswich ─────────────────────────────────────────────────────────
  {
    id: 'station-047',
    name: 'Costco Bundamba',
    brand: 'Costco',
    address: '1 Distribution Street',
    suburb: 'Bundamba',
    postcode: '4304',
    state: 'QLD',
    latitude: -27.6130,
    longitude: 152.7830,
    hasToilet: false,
    hasShop: false,
    hasCarwash: false,
  },
  {
    id: 'station-048',
    name: 'United Petroleum Ipswich',
    brand: 'United',
    address: '76 Brisbane Street',
    suburb: 'Ipswich',
    postcode: '4305',
    state: 'QLD',
    latitude: -27.6140,
    longitude: 152.7620,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-049',
    name: 'BP Ipswich',
    brand: 'BP',
    address: '120 Brisbane Street',
    suburb: 'Ipswich',
    postcode: '4305',
    state: 'QLD',
    latitude: -27.6120,
    longitude: 152.7600,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-050',
    name: 'Shell Coles Express Ipswich',
    brand: 'Coles Express',
    address: '205 Brisbane Street',
    suburb: 'Ipswich',
    postcode: '4305',
    state: 'QLD',
    latitude: -27.6100,
    longitude: 152.7580,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-051',
    name: 'Puma Goodna',
    brand: 'Puma',
    address: '21 Brisbane Road',
    suburb: 'Goodna',
    postcode: '4300',
    state: 'QLD',
    latitude: -27.6100,
    longitude: 152.8930,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-052',
    name: 'Ampol Goodna',
    brand: 'Ampol',
    address: '55 Brisbane Road',
    suburb: 'Goodna',
    postcode: '4300',
    state: 'QLD',
    latitude: -27.6080,
    longitude: 152.8910,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-053',
    name: '7-Eleven Springfield',
    brand: '7-Eleven',
    address: '1 Main Street',
    suburb: 'Springfield',
    postcode: '4300',
    state: 'QLD',
    latitude: -27.6560,
    longitude: 152.9080,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-054',
    name: 'BP Springfield',
    brand: 'BP',
    address: '35 Springfield Greenbank Arterial',
    suburb: 'Springfield',
    postcode: '4300',
    state: 'QLD',
    latitude: -27.6580,
    longitude: 152.9100,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-055',
    name: 'Liberty Bundamba',
    brand: 'Liberty',
    address: '38 Warwick Road',
    suburb: 'Bundamba',
    postcode: '4304',
    state: 'QLD',
    latitude: -27.6150,
    longitude: 152.7860,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-056',
    name: 'Independent Ipswich',
    brand: 'Independent',
    address: '310 Brisbane Street',
    suburb: 'Ipswich',
    postcode: '4305',
    state: 'QLD',
    latitude: -27.6090,
    longitude: 152.7550,
    hasToilet: false,
    hasShop: false,
    hasCarwash: false,
  },

  // ─── Redcliffe / Moreton ─────────────────────────────────────────────
  {
    id: 'station-057',
    name: 'BP Redcliffe',
    brand: 'BP',
    address: '138 Anzac Avenue',
    suburb: 'Redcliffe',
    postcode: '4020',
    state: 'QLD',
    latitude: -27.2310,
    longitude: 153.1050,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-058',
    name: 'Shell Redcliffe',
    brand: 'Shell',
    address: '200 Anzac Avenue',
    suburb: 'Redcliffe',
    postcode: '4020',
    state: 'QLD',
    latitude: -27.2290,
    longitude: 153.1040,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-059',
    name: 'Ampol Caboolture',
    brand: 'Ampol',
    address: '60 King Street',
    suburb: 'Caboolture',
    postcode: '4510',
    state: 'QLD',
    latitude: -27.0850,
    longitude: 152.9500,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-060',
    name: 'BP Caboolture',
    brand: 'BP',
    address: '112 Morayfield Road',
    suburb: 'Caboolture',
    postcode: '4510',
    state: 'QLD',
    latitude: -27.0830,
    longitude: 152.9480,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-061',
    name: '7-Eleven Caboolture',
    brand: '7-Eleven',
    address: '78 King Street',
    suburb: 'Caboolture',
    postcode: '4510',
    state: 'QLD',
    latitude: -27.0860,
    longitude: 152.9510,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-062',
    name: 'Shell Coles Express North Lakes',
    brand: 'Coles Express',
    address: '8 Endeavour Boulevard',
    suburb: 'North Lakes',
    postcode: '4509',
    state: 'QLD',
    latitude: -27.2280,
    longitude: 153.0300,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-063',
    name: 'BP North Lakes',
    brand: 'BP',
    address: '22 Lakefield Drive',
    suburb: 'North Lakes',
    postcode: '4509',
    state: 'QLD',
    latitude: -27.2260,
    longitude: 153.0280,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-064',
    name: 'Puma North Lakes',
    brand: 'Puma',
    address: '50 Anzac Avenue',
    suburb: 'North Lakes',
    postcode: '4509',
    state: 'QLD',
    latitude: -27.2300,
    longitude: 153.0320,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-065',
    name: 'United Petroleum Caboolture',
    brand: 'United',
    address: '135 Morayfield Road',
    suburb: 'Caboolture',
    postcode: '4510',
    state: 'QLD',
    latitude: -27.0810,
    longitude: 152.9460,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-066',
    name: 'Metro Redcliffe',
    brand: 'Metro',
    address: '55 Oxley Avenue',
    suburb: 'Redcliffe',
    postcode: '4020',
    state: 'QLD',
    latitude: -27.2350,
    longitude: 153.1080,
    hasToilet: false,
    hasShop: true,
    hasCarwash: false,
  },

  // ─── Gold Coast ──────────────────────────────────────────────────────
  {
    id: 'station-067',
    name: 'BP Southport',
    brand: 'BP',
    address: '105 Nerang Street',
    suburb: 'Southport',
    postcode: '4215',
    state: 'QLD',
    latitude: -27.9660,
    longitude: 153.3990,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-068',
    name: 'Shell Coles Express Southport',
    brand: 'Coles Express',
    address: '150 Nerang Street',
    suburb: 'Southport',
    postcode: '4215',
    state: 'QLD',
    latitude: -27.9680,
    longitude: 153.4010,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-069',
    name: '7-Eleven Southport',
    brand: '7-Eleven',
    address: '78 Ferry Road',
    suburb: 'Southport',
    postcode: '4215',
    state: 'QLD',
    latitude: -27.9640,
    longitude: 153.3970,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-070',
    name: 'Ampol Surfers Paradise',
    brand: 'Ampol',
    address: '3 Cavill Avenue',
    suburb: 'Surfers Paradise',
    postcode: '4217',
    state: 'QLD',
    latitude: -28.0020,
    longitude: 153.4290,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-071',
    name: 'BP Surfers Paradise',
    brand: 'BP',
    address: '35 Gold Coast Highway',
    suburb: 'Surfers Paradise',
    postcode: '4217',
    state: 'QLD',
    latitude: -28.0050,
    longitude: 153.4310,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-072',
    name: '7-Eleven Surfers Paradise',
    brand: '7-Eleven',
    address: '50 Gold Coast Highway',
    suburb: 'Surfers Paradise',
    postcode: '4217',
    state: 'QLD',
    latitude: -28.0000,
    longitude: 153.4270,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-073',
    name: 'Shell Broadbeach',
    brand: 'Shell',
    address: '2685 Gold Coast Highway',
    suburb: 'Broadbeach',
    postcode: '4218',
    state: 'QLD',
    latitude: -28.0270,
    longitude: 153.4330,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-074',
    name: 'United Petroleum Broadbeach',
    brand: 'United',
    address: '2710 Gold Coast Highway',
    suburb: 'Broadbeach',
    postcode: '4218',
    state: 'QLD',
    latitude: -28.0290,
    longitude: 153.4350,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-075',
    name: 'BP Robina',
    brand: 'BP',
    address: '10 Robina Town Centre Drive',
    suburb: 'Robina',
    postcode: '4226',
    state: 'QLD',
    latitude: -28.0730,
    longitude: 153.3850,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-076',
    name: 'Shell Coles Express Robina',
    brand: 'Coles Express',
    address: '30 Robina Town Centre Drive',
    suburb: 'Robina',
    postcode: '4226',
    state: 'QLD',
    latitude: -28.0750,
    longitude: 153.3870,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-077',
    name: 'Ampol Woolworths Robina',
    brand: 'Ampol',
    address: '55 Robina Town Centre Drive',
    suburb: 'Robina',
    postcode: '4226',
    state: 'QLD',
    latitude: -28.0770,
    longitude: 153.3830,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-078',
    name: 'Puma Nerang',
    brand: 'Puma',
    address: '49 Price Street',
    suburb: 'Nerang',
    postcode: '4211',
    state: 'QLD',
    latitude: -27.9960,
    longitude: 153.3370,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-079',
    name: 'Shell Nerang',
    brand: 'Shell',
    address: '75 Station Street',
    suburb: 'Nerang',
    postcode: '4211',
    state: 'QLD',
    latitude: -27.9940,
    longitude: 153.3350,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-080',
    name: '7-Eleven Nerang',
    brand: '7-Eleven',
    address: '100 Station Street',
    suburb: 'Nerang',
    postcode: '4211',
    state: 'QLD',
    latitude: -27.9980,
    longitude: 153.3390,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-081',
    name: 'BP Coomera',
    brand: 'BP',
    address: '122 Days Road',
    suburb: 'Coomera',
    postcode: '4209',
    state: 'QLD',
    latitude: -27.8960,
    longitude: 153.3570,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-082',
    name: 'Shell Coles Express Coomera',
    brand: 'Coles Express',
    address: '145 Foxwell Road',
    suburb: 'Coomera',
    postcode: '4209',
    state: 'QLD',
    latitude: -27.8940,
    longitude: 153.3550,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-083',
    name: 'Ampol Coomera',
    brand: 'Ampol',
    address: '88 Foxwell Road',
    suburb: 'Coomera',
    postcode: '4209',
    state: 'QLD',
    latitude: -27.8980,
    longitude: 153.3590,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-084',
    name: 'United Petroleum Oxenford',
    brand: 'United',
    address: '200 Tamborine Oxenford Road',
    suburb: 'Oxenford',
    postcode: '4210',
    state: 'QLD',
    latitude: -27.8870,
    longitude: 153.3180,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-085',
    name: 'BP Oxenford',
    brand: 'BP',
    address: '168 Old Pacific Highway',
    suburb: 'Oxenford',
    postcode: '4210',
    state: 'QLD',
    latitude: -27.8850,
    longitude: 153.3160,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-086',
    name: 'Liberty Nerang',
    brand: 'Liberty',
    address: '120 Nerang Street',
    suburb: 'Nerang',
    postcode: '4211',
    state: 'QLD',
    latitude: -27.9920,
    longitude: 153.3330,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-087',
    name: 'Metro Southport',
    brand: 'Metro',
    address: '220 Olsen Avenue',
    suburb: 'Southport',
    postcode: '4215',
    state: 'QLD',
    latitude: -27.9700,
    longitude: 153.4030,
    hasToilet: false,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-088',
    name: 'Puma Coomera',
    brand: 'Puma',
    address: '60 Reserve Road',
    suburb: 'Coomera',
    postcode: '4209',
    state: 'QLD',
    latitude: -27.9000,
    longitude: 153.3600,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
  },

  // ─── Additional spread stations ──────────────────────────────────────
  {
    id: 'station-089',
    name: 'BP Moorooka',
    brand: 'BP',
    address: '155 Beaudesert Road',
    suburb: 'Moorooka',
    postcode: '4105',
    state: 'QLD',
    latitude: -27.5260,
    longitude: 153.0280,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-090',
    name: 'Shell Coles Express Annerley',
    brand: 'Coles Express',
    address: '490 Ipswich Road',
    suburb: 'Annerley',
    postcode: '4103',
    state: 'QLD',
    latitude: -27.5100,
    longitude: 153.0310,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-091',
    name: '7-Eleven Stafford',
    brand: '7-Eleven',
    address: '400 Stafford Road',
    suburb: 'Stafford',
    postcode: '4053',
    state: 'QLD',
    latitude: -27.4150,
    longitude: 153.0160,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-092',
    name: 'Ampol Woolworths Eight Mile Plains',
    brand: 'Ampol',
    address: '2650 Logan Road',
    suburb: 'Eight Mile Plains',
    postcode: '4113',
    state: 'QLD',
    latitude: -27.5780,
    longitude: 153.0960,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-093',
    name: 'Puma Rocklea',
    brand: 'Puma',
    address: '1444 Ipswich Road',
    suburb: 'Rocklea',
    postcode: '4106',
    state: 'QLD',
    latitude: -27.5400,
    longitude: 153.0110,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-094',
    name: 'Shell Coles Express Clayfield',
    brand: 'Coles Express',
    address: '312 Sandgate Road',
    suburb: 'Clayfield',
    postcode: '4011',
    state: 'QLD',
    latitude: -27.4300,
    longitude: 153.0540,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-095',
    name: 'BP Mitchelton',
    brand: 'BP',
    address: '194 Samford Road',
    suburb: 'Mitchelton',
    postcode: '4053',
    state: 'QLD',
    latitude: -27.4170,
    longitude: 152.9820,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'bpme',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-096',
    name: 'United Petroleum Slacks Creek',
    brand: 'United',
    address: '750 Kingston Road',
    suburb: 'Slacks Creek',
    postcode: '4127',
    state: 'QLD',
    latitude: -27.6330,
    longitude: 153.1450,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
  },
  {
    id: 'station-097',
    name: '7-Eleven Beenleigh',
    brand: '7-Eleven',
    address: '123 City Road',
    suburb: 'Beenleigh',
    postcode: '4207',
    state: 'QLD',
    latitude: -27.7140,
    longitude: 153.1960,
    hasToilet: true,
    hasShop: true,
    hasCarwash: false,
    loyaltyProgram: 'price_lock',
    loyaltyDiscountCents: 0,
  },
  {
    id: 'station-098',
    name: 'Ampol Beenleigh',
    brand: 'Ampol',
    address: '190 City Road',
    suburb: 'Beenleigh',
    postcode: '4207',
    state: 'QLD',
    latitude: -27.7160,
    longitude: 153.1980,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'ampcharge',
    loyaltyDiscountCents: 2,
  },
  {
    id: 'station-099',
    name: 'Shell Coles Express Oxley',
    brand: 'Coles Express',
    address: '1640 Ipswich Road',
    suburb: 'Oxley',
    postcode: '4075',
    state: 'QLD',
    latitude: -27.5470,
    longitude: 152.9780,
    hasToilet: true,
    hasShop: true,
    hasCarwash: true,
    loyaltyProgram: 'flybuys',
    loyaltyDiscountCents: 4,
  },
  {
    id: 'station-100',
    name: 'Independent Loganholme',
    brand: 'Independent',
    address: '3770 Pacific Highway',
    suburb: 'Loganholme',
    postcode: '4129',
    state: 'QLD',
    latitude: -27.6810,
    longitude: 153.1690,
    hasToilet: false,
    hasShop: false,
    hasCarwash: false,
  },
];
